version: "3.8"
services:
    backend:
        container_name: fire_backend
        image: "python:3.10"
        volumes: 
            - ./server:/server
        ports: 
            - "49255:8000"
        command: >
            sh -c "apt-get install -y libmariadb-dev && 
                    cd server &&
                    pip install -r requirements.txt &&
                    cd src &&
                    uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        restart: unless-stopped
    db:
        container_name: fire_db
        image: lscr.io/linuxserver/mariadb:latest
        environment:
            - PUID=1000
            - PGID=1000
            - MYSQL_ROOT_PASSWORD=root      # This is a placeholder for development.
            - TZ=America/Toronto
            - MYSQL_DATABASE=portfolio      # optional
            - MYSQL_USER=admin              # optional. This is a placeholder for development.
            - MYSQL_PASSWORD=password       # optional. This is a placeholder for development.
        ports:
            - "43306:3306"
        restart: unless-stopped

networks:
    default:
        driver: bridge