name: Docker Compose CI

on: [push]

jobs:
    docker:
        timeout-minutes: 5
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Start containers
              run: make deploy
              
            - name: Stop containers
              run: make teardown
