name: Docker Compose CI

on: [push]

jobs:
    docker:
        timeout-minutes: 5
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Start containers
              run: make deploy
            
            - name: Hello World
              run: |
                if curl -s localhost:49255/accounts | grep -o "Hello World"; then \
                  echo "Succeeded"; else \
                  exit 1; fi

            - name: Stop containers
              run: make teardown
